### ISSUE TITLE
프로필에서 좋아요/싫어요 등록한 게시물과 리뷰 요청 시 좋아요/싫어요 구분

### ISSUE THREAD

**Issue by QuaRang1225** [NCookies/imad-server#119]
### 문제점

- 현재 좋아요/싫어요한 게시물과 리뷰의 결과값이 한 리스트에 나옴
- 뷰에서 좋아요와 싫어요를 구분하는 필터를 추가할 예정
- 한 페이지의 데이터 수가 10개가 넘어갈 경우 다음 페이지를 요청하는데 한 리스트에 좋아요와 싫어요가 혼합 되어 응답해주기 때문에 필터로 구분하기 다소 어려움이 있음

### 해결방안
- likeStatus 쿼리스트링을 추가하여 좋아요와 싫어요 요청을 구분해서 requset,response 하는 방향으로 추진 희망

### 기존
![Image](https://github.com/NCookies/imad-server/assets/31721255/b2e4a9bb-4936-404b-a848-976faba98b31)

### 변경 후 예상요청

![Image](https://github.com/NCookies/imad-server/assets/31721255/92fdad10-c4ee-4177-ad51-f73518c06f06)

- 해당 사진은 의견일 뿐이며, 개발자 임의로 수정 한 뒤 응답 바람
- 전체 리스트 반환이 필요할 경우 "like_status" 필드에 0추가 검토 요망

**Comment by NCookies** [comment]
추가사항 내용을 별도의 이슈로 분리함

**Comment by NCookies** [comment]
`{{baseUrl}}/api/profile/like/posting/list?page=1&like_status=1`
`{{baseUrl}}/api/profile/like/review/list?page=1&like_status=1`

위의 요청에서 like_status가 0이면 좋아요/싫어요 구분 없이 전체 조회, 1이면 좋아요, -1이면 싫어요를 등록한 게시글과 리뷰 리스트를 조회한다. 

9ee3c41 커밋 참고
