### ISSUE TITLE
리뷰 삭제 버그

### ISSUE THREAD

**Issue by QuaRang1225** [NCookies/imad-server#52]
리뷰 추가수정삭제 할때마다 작품 평점 갱신해주는데, 작품에 대한 유일한 리뷰가 삭제될 때 발생하는 버그가 생김
```json
{
    "status": 401,
    "data": null,
    "message": "잘못된 요청이거나 올바르지 않은 인증정보입니다."
}
```

**Comment by NCookies** [comment]
작품에 대한 리뷰를 삭제했을 때 해당 작품에 대한 리뷰가 더 이상 없다면 이 에러가 발생하는 것을 확인했다. 

### 원인

리뷰가 추가/수정/삭제 될 때마다 Contents(작품) 테이블의 reviewCnt와 imadScore를 갱신해주는데, score 평균값을 계산하는 메소드에서 리뷰가 존재하지 않으니 null 값이 리턴된다. 그러나 Entity 클래스에서 imadScore는 float 자료형을 사용하기 때문에 에러가 발생한다.

### 해결

이는 #40 와도 같은 맥락의 이슈이다. 마찬가지로 primitive type인 `float`을 null값을 담을 수 있는 wrapper type인 `Float`으로 수정해주면 해결될 것으로 보인다.
