### ISSUE TITLE
작품검색 에러

### ISSUE THREAD

**Issue by QuaRang1225** [NCookies/imad-server#83]
> {{baseUrl}}/api/contents/search?query=죠&type=multi&page=1

작품 검색 요청 시 다음과 같이 반환됨

```json
{
    "status": 401,
    "data": null,
    "message": "잘못된 요청이거나 올바르지 않은 인증정보입니다."
}
```
- 같은 토큰으로 다른 요청은 잘 되는 것 확인 
- 아직은 작품 검색 부분만 문제가 있는 것으로 추정됨

**Comment by NCookies** [comment]
TMDB API 요청 시 `page - 1`를 파라미터로 날리기 때문에 발생한 문제로 파악된다.

b21614d 커밋에서 일괄적으로 수정할 때 같이 변경된 것으로 보이며, 해당 부분 정정 후 정상적으로 동작하는 것을 확인했다.

#81 side effect임

**Comment by NCookies** [comment]
AWS 서버에서 정상 동작 확인 완료
