### ISSUE TITLE
게시물 좋아요/싫어요 요청 시 수정날짜 갱신됨

### ISSUE THREAD

**Issue by QuaRang1225** [NCookies/imad-server#85]
- 게시물에서 (본인이 아닐경우도 포함) 좋아요/싫어요 요청을 보내면 "modified_at" 필드가 갱신됨
- 게시물 상세 조회, 게시물 (조건)전체 리스트 조회 요청 등 전부 해당 잇슈에 포함됨

**Comment by QuaRang1225** [comment]
- 요청을 할때마다 계속 수정 시간("modified_at" 필드) 갱신됨

**Comment by NCookies** [comment]
정확하게는 게시글 조회(단일)를 할 때에만 수정시간("modified_at" 필드)이 갱신되고 있다. 

특정 게시글을 조회할 때마다 조회수 count를 1씩 늘려주고 있는데, 이 떄 JPA 자체 메소드인 save(...)를 사용해서 JPA Auditing인 `@LastModifiedDate` 필드가 수정되고 있는 것으로 파악된다.

```java
            // 조회수 갱신
            posting.setViewCnt(posting.getViewCnt() + 1);
            postingRepository.save(posting);
```
