### ISSUE TITLE
게시물 댓글  관련 잇슈2

### ISSUE THREAD

**Issue by QuaRang1225** [NCookies/imad-server#94]
remove된 댓글은 "comment_cnt"에 포함을 안시키는 방향 요구
- 예를들어 전체 댓글수가 5라고 하고 그중 2개가 삭제된 댓글이면 뷰에는 3개의 댓글만 보여지지만 comment_id는 여전히 5이고 클라이언트에선 그것을 구분짓기가 힘듬 

#### 해결방안
- 애초에 삭제된 댓글은 comment_cnt에 포함하지 않음
-  삭제된 댓글수와 삭제되지 않은 댓글수를 분리하여 response

**Comment by NCookies** [comment]
게시글의 commentCnt 필드는 삭제된 댓글 수를 제외함

**Comment by QuaRang1225** [comment]
확인
